/*
	First version of the class.  
	We start with an empty implementation - just returning null.  Our first unit test to test that "I" is converte to "1" will fail


	Business requirements for the ConvertNumeralToInteger class are as follow:

	x	When passed "I", the class should return 1
	-	When passed "II", the class should return 2
	-	When passed "III", the class should return 3
	-	When passed "IV", the class should return 4
	-	When passed "V", the class should return 5
	-	When passed "VI", the class should return 6
	-	When passed "VII", the class should return 7
	-	When passed "VIII", the class should return 8
	-	When passed "IX", the class should return 9
	-	When passed "X", the class should return 10
*/

public class NumeralConverterV1
{
	public static Integer ConvertNumeralToInteger(String numeral)
	{
		return null;
	}
}